services:
  anythingllm:
    image: docker.io/mintplexlabs/anythingllm:1.12 # https://hub.docker.com/r/mintplexlabs/anythingllm/tags
    pull_policy: always
    container_name: anythingllm
    restart: always
    networks:
      - anythingllm
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/anythingllm/volumes/data:/app/server/storage
      - ${DATA_PATH}/anythingllm/volumes/env:/app/server/.env

networks:
  anythingllm:
    external: true