# https://artifacthub.io/packages/helm/cert-manager/cert-manager
# https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/

fullnameOverride: cert-manager
namespace: cert-manager

# Install and keep CRDs
crds:
  enabled: true
  keep: true

nodeSelector:
  node-role.kubernetes.io/homelab: homelab