services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:5a14ee9c6a1ce413a93d3229eb49dea935fc304e # ghcr.io/danny-avila/librechat-dev
    pull_policy: always
    container_name: librechat
    restart: always
    user: "${UID}:${GID}"
    networks:
      - librechat
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/librechat/volumes/librechat/images:/app/client/public/images:Z
      - ${DATA_PATH}/librechat/volumes/librechat/logs:/app/api/logs:Z
      - ${DATA_PATH}/librechat/configs/librechat.yaml:/app/librechat.yaml:Z
    depends_on:
      - librechat-mongodb
      - librechat-rag

  librechat-mongodb:
    container_name: librechat-mongodb
    image: docker.io/mongo:8.0.12-noble # https://hub.docker.com/_/mongo/tags
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_PATH}/librechat/volumes/mongodb:/data/db:Z
    command: mongod --noauth
    networks:
      - librechat

  librechat-meilisearch:
    container_name: librechat-meilisearch
    image: docker.io/getmeili/meilisearch:v1.18.0 # https://hub.docker.com/r/getmeili/meilisearch/tags
    env_file:
      - config.env
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_PATH}/librechat/volumes/meilisearch:/meili_data:Z
    restart: always
    networks:
      - librechat
    # command: ["meilisearch", "--experimental-dumpless-upgrade"]

  librechat-pgvector:
    container_name: librechat-pgvector
    image: docker.io/pgvector/pgvector:0.8.0-pg17
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/librechat/volumes/pgvector:/var/lib/postgresql/data:Z
    restart: always
    networks:
      - librechat

  librechat-rag:
    container_name: librechat-rag
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:2f08fc37b77771fd79c9ddd1e2daf3346ae1953a # ghcr.io/danny-avila/librechat-rag-api-dev-lite
    pull_policy: always
    restart: always
    networks:
      - librechat
    env_file:
      - config.env
    depends_on:
      - librechat-pgvector

networks:
  librechat:
    external: true