FROM docker.io/caddy:2.11.4-builder-alpine@sha256:7bac9be4072f7c4db2ccc7350750e0705004bf02da2ac7d96b1469ca4f28bb7c AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-webdav@fa2f366b0d75e54c2e381c0aefc3a8df8bf5794b \
    --with github.com/caddy-dns/cloudflare@v0.2.4

FROM docker.io/caddy:2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648

RUN addgroup -S -g 1000 caddy && \
    adduser -S -D -H -u 1000 -G caddy caddy

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
USER caddy:caddy
