FROM docker.io/caddy:2.11.6-builder-alpine@sha256:b0a9daab97b413316e23238e5d466849b0ebbba8d411f7344e084d9f51fe973a AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-webdav@fa2f366b0d75e54c2e381c0aefc3a8df8bf5794b \
    --with github.com/caddy-dns/cloudflare@v0.2.4

FROM docker.io/caddy:2.11.6-alpine@sha256:c776e0c6413b544d0459665e54ec7b8b2a15000c0cbee8b254da0067b1d184ff

RUN addgroup -S -g 1000 caddy && \
    adduser -S -D -H -u 1000 -G caddy caddy

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
USER caddy:caddy
