FROM docker.io/caddy:2.11.4-builder-alpine@sha256:2b9f32cbba6045e79212bb253f595588d20be8f7d1edf61582c519e124e0d2d8 AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-webdav@fa2f366b0d75e54c2e381c0aefc3a8df8bf5794b \
    --with github.com/caddy-dns/cloudflare@v0.2.4

FROM docker.io/caddy:2.11.4-alpine@sha256:de23def33b17fb5d1290b0f6c2add1d70780e52341896c00a4c8a2a2fe9d355e

RUN addgroup -S -g 1000 caddy && \
    adduser -S -D -H -u 1000 -G caddy caddy

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
USER caddy:caddy
