runner:
  capacity: 1
  timeout: 2h
  shutdown_timeout: 30m

  labels:
    - "forgejo-ci:docker://docker.io/library/node:26-trixie@sha256:fa271c47a5d81dc321f4a45be01362f5b3de7559edc7e76b8c4089be1e50d866"

container:
  network: ""
  enable_ipv6: false
  privileged: false
  valid_volumes: []
  docker_host: "-"
  force_pull: true
  options: >-
    --cpus=4
    --memory=16g
    --pids-limit=1024

cache:
  enabled: false

server:
  connections:
    homelab:
      url: "https://git.${BASE_DOMAIN}/"
      uuid: "${FORGEJO_RUNNER_UUID}"
      token: "${FORGEJO_RUNNER_SECRET}"
