runner:
  capacity: 1
  timeout: 2h
  shutdown_timeout: 30m

  labels:
    - "forgejo-ci:docker://docker.io/library/node:26-trixie@sha256:a723b54c35a76e947095a20a67d39585bb09c862e6b1adeb8a9f518f95e34fb0"

container:
  network: ""
  enable_ipv6: false
  privileged: false
  valid_volumes: []
  docker_host: "-"
  force_pull: true
  options: >-
    --cpus=4
    --memory=16g
    --pids-limit=1024

cache:
  enabled: false

server:
  connections:
    homelab:
      url: "https://git.${BASE_DOMAIN}/"
      uuid: "${FORGEJO_RUNNER_UUID}"
      token: "${FORGEJO_RUNNER_SECRET}"
