runner:
  capacity: 1
  timeout: 2h
  shutdown_timeout: 30m

  labels:
    - "forgejo-ci:docker://docker.io/library/node:26-trixie@sha256:9965105b7a4e201d7f07268402bb4971670592b46c9b9058cc643961199a1ab6"

container:
  network: ""
  enable_ipv6: false
  privileged: false
  valid_volumes: []
  docker_host: "-"
  force_pull: true
  options: >-
    --cpus=4
    --memory=16g
    --pids-limit=1024

cache:
  enabled: false

server:
  connections:
    homelab:
      url: "https://git.${BASE_DOMAIN}/"
      uuid: "${FORGEJO_RUNNER_UUID}"
      token: "${FORGEJO_RUNNER_SECRET}"
