# References:
# https://dnscrypt.info/doc
# https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

# Ports:
# DNS: 53
# DoH: 3000
# UI: 8080

################################################
##### Global Settings
################################################

# https://dnscrypt.info/public-servers/
# https://www.privacyguides.org/en/dns/#recommended-providers
# List of servers to use
server_names = ['quad9-doh-ip4-port443-filter-ecs-pri', 'cloudflare-security', 'controld-block-malware-ad', 'mullvad-base-doh', 'dns0']

# List of local addresses and ports to listen to
listen_addresses = ['0.0.0.0:53']

# Maximum number of simultaneous client connections to accept
max_clients = 250

################################################
##### Server Selection
################################################

# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6
ipv6_servers = false

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = false

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true

# Use servers implementing the Oblivious DoH protocol
odoh_servers = false

# Server must support DNS security extensions (DNSSEC)
require_dnssec = true

# Server must not log user queries (declarative)
require_nolog = true

# Server must not enforce its own blocklist (for parental control, ads blocking...)
require_nofilter = false

# Server names to avoid even if they match all criteria
disabled_server_names = []

################################################
##### Connection Settings
################################################

# Always use TCP to connect to upstream servers
force_tcp = false

# Enable *experimental* support for HTTP/3 (HTTP over QUIC)
http3 = false

# When http3 is true, always try HTTP/3 first for DoH servers
http3_probe = false

# How long a DNS query will wait for a response, in milliseconds
timeout = 5000

# Keepalive for HTTP (HTTPS, HTTP/2, HTTP/3) queries, in seconds
keepalive = 30

################################################
##### Load Balancing & Performance
################################################

# Load-balancing strategy: 'wp2' (default), 'p2', 'ph', 'p<n>', 'first', 'random'
lb_strategy = 'random'

# Constantly try to estimate the latency of all the resolvers
lb_estimator = false

# Hot reloading of configuration files
enable_hot_reload = false

################################################
##### Logging
################################################

# Maximum log files size in MB - Set to 0 for unlimited.
log_files_max_size = 10

# How long to keep backup files, in days
log_files_max_age = 7

# Maximum log files backups to keep (or 0 to keep all backups)
log_files_max_backups = 1

################################################
##### Certificate & Management
################################################

# Delay, in minutes, after which certificates are reloaded
cert_refresh_delay = 240

################################################
##### Startup & Network
################################################

# Bootstrap resolvers used to retrieve initial resolvers list
bootstrap_resolvers = ['9.9.9.11:53', '1.1.1.1:53', '8.8.8.8:53']

# Whether to ignore system DNS
ignore_system_dns = true

# Maximum time (in seconds) to wait for network connectivity before initializing the proxy
netprobe_timeout = 60

# Address and port to try initializing a connection to, just to check if the network is up
netprobe_address = '9.9.9.9:53'

################################################
##### Filters
################################################

## Immediately respond to IPv6-related queries with an empty response
block_ipv6 = false

## Immediately respond to A and AAAA queries for host names without a domain name
block_unqualified = true

# Immediately respond to queries for local zones instead of leaking them to upstream resolvers (always causing errors or timeouts)
block_undelegated = true

# TTL for synthetic responses sent when a request has been blocked (due to IPv6 or blocklists)
reject_ttl = 10

################################################
##### DNS Cache
################################################

# Enable a DNS cache to reduce latency and outgoing traffic
cache = true

# Cache size
cache_size = 4096

# Minimum TTL for cached entries
cache_min_ttl = 2400

# Maximum TTL for cached entries
cache_max_ttl = 86400

# Minimum TTL for negatively cached entries
cache_neg_min_ttl = 60

# Maximum TTL for negatively cached entries
cache_neg_max_ttl = 600

################################################
##### Captive Portal
################################################

[captive_portals]

################################################
##### Local DoH
################################################

[local_doh]

# Addresses that the local DoH server should listen to
listen_addresses = ['0.0.0.0:3000']

# Path of the DoH URL
path = '/dns-query'

# Certificate file and key - Note that the certificate has to be trusted
# Can be generated using the following command:
# openssl req -x509 -nodes -newkey rsa:2048 -days 5000 -sha256 -keyout localhost.pem -out localhost.pem
cert_file = '/etc/dnscrypt-proxy/localhost.pem'
cert_key_file = '/etc/dnscrypt-proxy/localhost.pem'

################################################
##### Query Logging
################################################

[query_log]

# Query log format (currently supported: tsv and ltsv)
format = 'tsv'

################################################
##### Suspicious Queries Logging
################################################

[nx_log]

# Query log format (currently supported: tsv and ltsv)
format = 'tsv'

################################################
##### Pattern-based Blocking (blocklists)
################################################

[blocked_names]

################################################
##### Pattern-based IP blocking (IP blocklists)
################################################

[blocked_ips]

################################################
##### Pattern-based allow lists (blocklists bypass)
################################################

[allowed_names]

################################################
##### Pattern-based allowed IPs lists (blocklists bypass)
################################################

[allowed_ips]

################################################
##### Time access restrictions
################################################

[schedules]

################################################
##### Servers
################################################

[sources]

# An example of a remote source from https://github.com/DNSCrypt/dnscrypt-resolvers
[sources.public-resolvers]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
]
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

# Anonymized DNS relays
[sources.relays]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md',
  'https://download.dnscrypt.info/resolvers-list/v3/relays.md',
]
cache_file = '/var/cache/dnscrypt-proxy/relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

################################################
##### Servers with known bugs
################################################

[broken_implementations]
fragments_blocked = [
  'cisco',
  'cisco-ipv6',
  'cisco-familyshield',
  'cisco-familyshield-ipv6',
  'cleanbrowsing-adult',
  'cleanbrowsing-adult-ipv6',
  'cleanbrowsing-family',
  'cleanbrowsing-family-ipv6',
  'cleanbrowsing-security',
  'cleanbrowsing-security-ipv6',
]

################################################
##### Certificate-based client authentication for DoH
################################################

[doh_client_x509_auth]

################################################
##### Anonymized DNS
################################################

[anonymized_dns]

# Skip resolvers incompatible with anonymization instead of using them directly
skip_incompatible = false

################################################
##### DNS64
################################################

[dns64]

################################################
##### Monitoring UI
################################################

[monitoring_ui]

# Enable the monitoring UI
enabled = true

# Listen address for the monitoring UI
listen_address = "127.0.0.1:8080"

# Optional username and password for basic authentication
username = "${DNSCRYPT_UI_USER}"
password = "${DNSCRYPT_UI_PASSWORD}"

# Optional TLS certificate and key for HTTPS. If both are empty, HTTP will be used
tls_certificate = ""
tls_key = ""

# Enable query logging in the monitoring UI
enable_query_log = true

# Privacy level for the monitoring UI
privacy_level = 1

# Maximum number of recent query log entries to keep in memory
max_query_log_entries = 10000

# Maximum memory usage in MB for recent query logs
max_memory_mb = 20

################################################
##### Static Entries
################################################

[static]