# https://artifacthub.io/packages/helm/external-dns/external-dns
# https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md

fullnameOverride: external-dns
namespaced: true

sources:
  - service
  - ingress

# "sync" policy has issues:
# https://github.com/kubernetes-sigs/external-dns/issues/4059
policy: upsert-only

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

nodeSelector:
  node-role.kubernetes.io/homelab: homelab