# References:
# HA: https://www.home-assistant.io/installation/linux#docker-compose
# Zigbee2MQTT: https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose
# Mosquitto: https://hub.docker.com/_/eclipse-mosquitto

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.8.2 # https://github.com/home-assistant/core/pkgs/container/home-assistant
    restart: always
    volumes:
      - ${DATA_PATH}/homeassistant/volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    depends_on:
      - homeassistant-mosquitto
    networks:
      - homeassistant

  homeassistant-zigbee2mqtt:
    container_name: homeassistant-zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:2.6.0 # https://github.com/koenkk/zigbee2mqtt/pkgs/container/zigbee2mqtt
    restart: always
    volumes:
      - ${DATA_PATH}/homeassistant/volumes/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/serial/by-id/${HOMEASSISTANT_ZIGBEE_ROUTER_SERIAL_ID}:/dev/ttyACM0
    depends_on:
      - homeassistant-mosquitto
    networks:
      - homeassistant

  homeassistant-mosquitto:
    container_name: homeassistant-mosquitto
    image: docker.io/library/eclipse-mosquitto:2.0.22 # https://hub.docker.com/_/eclipse-mosquitto
    restart: always
    volumes:
      - ${DATA_PATH}/homeassistant/volumes/mosquitto/config:/mosquitto/config
      - ${DATA_PATH}/homeassistant/volumes/mosquitto/data:/mosquitto/data
      - ${DATA_PATH}/homeassistant/volumes/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    networks:
      - homeassistant

networks:
  homeassistant:
    external: true