# TODO: replace with specific configs
# https://www.home-assistant.io/integrations/default_config/
default_config:

automation: !include automations.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ${HOMEASSISTANT_TRUSTED_PROXY_SUBNET}