services:
  caddy:
    build:
      context: ${DATA_PATH}/caddy/docker
    container_name: caddy
    restart: always
    ports:
      - 443:443
    networks:
      - caddy
      - pihole
      - technitium
    volumes:
      - ${DATA_PATH}/caddy/configs/Caddyfile:/etc/caddy/Caddyfile:Z
      - ${DATA_PATH}/caddy/volumes/caddy:/data/caddy:Z
      - ${DATA_PATH}/caddy/volumes/bookmarks:/data/bookmarks:Z

networks:
  caddy:
    external: true
  pihole:
    external: true
  technitium:
    external: true