services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:fe512005fca961c6c602bc0b70cd6ad29b6d643b
    pull_policy: always
    container_name: librechat
    restart: always
    user: "${UID}:${GID}"
    networks:
      - librechat
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/librechat/volumes/librechat/images:/app/client/public/images:Z
      - ${DATA_PATH}/librechat/volumes/librechat/logs:/app/api/logs:Z
      - ${DATA_PATH}/librechat/configs/librechat.yaml:/app/librechat.yaml:Z
    depends_on:
      - librechat-mongodb
      - librechat-rag

  librechat-mongodb:
    container_name: librechat-mongodb
    image: docker.io/mongo:8.0.8-noble
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_PATH}/librechat/volumes/mongodb:/data/db:Z
    command: mongod --noauth
    networks:
      - librechat

  librechat-meilisearch:
    container_name: librechat-meilisearch
    image: docker.io/getmeili/meilisearch:v1.12.8
    env_file:
      - config.env
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_PATH}/librechat/volumes/meilisearch:/meili_data:Z
    restart: always
    networks:
      - librechat

  librechat-pgvector:
    container_name: librechat-pgvector
    image: docker.io/pgvector/pgvector:0.8.0-pg17
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/librechat/volumes/pgvector:/var/lib/postgresql/data:Z
    restart: always
    networks:
      - librechat

  librechat-rag:
    container_name: librechat-rag
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:8ae9896691f10dc287a314355b999297d9daaab9
    pull_policy: always
    restart: always
    networks:
      - librechat
    env_file:
      - config.env
    depends_on:
      - librechat-pgvector

networks:
  librechat:
    external: true