services:
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:f4680b016cda71a132abe8719416169734a1f10a
    pull_policy: always
    container_name: librechat
    restart: always
    user: "${UID}:${GID}"
    networks:
      - librechat
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/librechat/volumes/librechat/images:/app/client/public/images:Z
      - ${DATA_PATH}/librechat/volumes/librechat/logs:/app/api/logs:Z
      - ${DATA_PATH}/librechat/configs/librechat.yaml:/app/librechat.yaml:Z
    depends_on:
      - librechat-mongodb
      - librechat-rag

  librechat-mongodb:
    container_name: librechat-mongodb
    image: docker.io/mongo:8.0.11-noble
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_PATH}/librechat/volumes/mongodb:/data/db:Z
    command: mongod --noauth
    networks:
      - librechat

  librechat-meilisearch:
    container_name: librechat-meilisearch
    image: docker.io/getmeili/meilisearch:v1.15.2
    env_file:
      - config.env
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_PATH}/librechat/volumes/meilisearch:/meili_data:Z
    restart: always
    networks:
      - librechat
    # command: ["meilisearch", "--experimental-dumpless-upgrade"]

  librechat-pgvector:
    container_name: librechat-pgvector
    image: docker.io/pgvector/pgvector:0.8.0-pg17
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/librechat/volumes/pgvector:/var/lib/postgresql/data:Z
    restart: always
    networks:
      - librechat

  librechat-rag:
    container_name: librechat-rag
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:33a221a6f5f5ee0af03e0cecca2508d9bc1f649b
    pull_policy: always
    restart: always
    networks:
      - librechat
    env_file:
      - config.env
    depends_on:
      - librechat-pgvector

networks:
  librechat:
    external: true