services:
  pihole:
    image: docker.io/pihole/pihole:2025.02.1
    pull_policy: always
    container_name: pihole
    restart: on-failure
    networks:
      - pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
    env_file:
      - config.env
    depends_on:
      - pihole-dnscrypt
    volumes:
      - ${DATA_PATH}/pihole/volumes/pihole:/etc/pihole:Z
      - ${DATA_PATH}/pihole/configs/99-edns.conf:/etc/dnsmasq.d/99-edns.conf:Z

  pihole-dnscrypt:
    build:
      context: ${DATA_PATH}/pihole/docker
    container_name: pihole-dnscrypt
    restart: on-failure
    networks:
      - pihole

networks:
  pihole:
    external: true