services:
  gitea:
    image: docker.io/gitea/gitea:1.23.6
    pull_policy: always
    container_name: gitea
    restart: always
    networks:
      - gitea
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/gitea/volumes/gitea:/data:Z
    depends_on:
      - gitea-postgres

  gitea-postgres:
    container_name: gitea-postgres
    image: docker.io/postgres:17.2-bookworm
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/gitea/volumes/postgres:/var/lib/postgresql/data:Z
    restart: always
    networks:
      - gitea

networks:
  gitea:
    external: true