FROM docker.io/alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add --no-cache py3-bcrypt=5.0.0-r1 radicale=3.7.5-r0

USER radicale:radicale
ENTRYPOINT ["radicale"]
