FROM docker.io/alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN addgroup -S -g 1000 zigbee && \
    adduser -S -D -H -u 1000 -G zigbee zigbee && \
    mkdir -p /srv && \
    printf 'e2e Zigbee2MQTT hardware fixture\n' > /srv/index.html

COPY server.sh /usr/local/bin/e2e-zigbee-server
RUN chmod 0755 /usr/local/bin/e2e-zigbee-server

USER 1000:1000
ENTRYPOINT ["/usr/local/bin/e2e-zigbee-server"]
