permit_join: false

mqtt:
  server: mqtt://homeassistant-mosquitto:1883
  base_topic: zigbee2mqtt
  user: ha
  password: ${HOMEASSISTANT_MOSQUITTO_PASSWORD}
  keepalive: 60
  version: 5

advanced:
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  output: json

frontend:
  enabled: true
  package: zigbee2mqtt-frontend
  port: 8080
  url: https://home-zigbee.${BASE_DOMAIN}

homeassistant:
  enabled: true
  discovery_topic: homeassistant
  status_topic: homeassistant/status

ota:
  update_check_interval: 1440
  disable_automatic_update_check: false

serial:
  port: /dev/ttyACM0
  adapter: ember
