services:
  obsidian:
    image: docker.io/couchdb:3.5.0
    container_name: obsidian
    volumes:
      - ${DATA_PATH}/obsidian/configs/local.ini:/opt/couchdb/etc/local.ini:Z
      - ${DATA_PATH}/obsidian/volumes/obsidian:/opt/couchdb/data:Z
    env_file:
      - config.env
    restart: always
    networks:
      - obsidian

networks:
  obsidian:
    external: true