# https://github.com/ente-io/ente/blob/main/server/config/compose.yaml
# https://github.com/ente-io/ente/blob/main/web/docs/docker.md

services:
  ente-postgres:
    container_name: ente-postgres
    image: docker.io/postgres:17.6-bookworm # https://hub.docker.com/_/postgres
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/ente/volumes/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -q -d ente -U ente
      start_period: 30s
      start_interval: 1s
    networks:
      - ente

  ente-museum:
    container_name: ente-museum
    image: ghcr.io/ente-io/server:1fe2a941ffa72f986be76099e7a75a21fc2fee8e # https://github.com/ente-io/ente/pkgs/container/server
    volumes:
      - ${DATA_PATH}/ente/configs/museum.yaml:/museum.yaml:ro
      - ${DATA_PATH}/ente/volumes/ente:/data
    networks:
      - ente
    depends_on:
      ente-postgres:
        condition: service_healthy

  ente-web:
    container_name: ente-web
    image: ghcr.io/ente-io/web:29b12fc6b571551a51b84c1b9abc4908c53fff24 # https://github.com/ente-io/ente/pkgs/container/web
    env_file:
      - config.env
    networks:
      - ente
    depends_on:
      - ente-museum

networks:
  ente:
    external: true