# https://github.com/ente-io/ente/blob/main/server/config/compose.yaml
# https://github.com/ente-io/ente/blob/main/web/docs/docker.md

services:
  ente-postgres:
    container_name: ente-postgres
    image: docker.io/postgres:17.5-bookworm
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/ente/volumes/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -q -d ente -U ente
      start_period: 30s
      start_interval: 1s
    networks:
      - ente

  ente-museum:
    container_name: ente-museum
    image: ghcr.io/ente-io/server:30262f82a56a83f2bfda190e247c926a8084bbfa
    volumes:
      - ${DATA_PATH}/ente/volumes/configs/museum.yaml:/museum.yaml:ro
      - ${DATA_PATH}/ente/volumes/ente:/data
    networks:
      - ente
    depends_on:
      ente-postgres:
        condition: service_healthy

  ente-web:
    container_name: ente-web
    image: ghcr.io/ente-io/web:d077d5dcbb5e18784d36348cafb9866677a3c25f
    networks:
      - ente
    depends_on:
      - ente-museum

networks:
  ente:
    external: true