services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.126.1
    volumes:
      - ${DATA_PATH}/immich/volumes/immich:/usr/src/app/upload:Z
    env_file:
      - config.env
    depends_on:
      - immich-redis
      - immich-postgres
    restart: on-failure
    networks:
      - immich

  immich-redis:
    container_name: immich-redis
    image: docker.io/redis:7.4.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: on-failure
    networks:
      - immich

  immich-postgres:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg15-v0.3.0
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/immich/volumes/postgres:/var/lib/postgresql/data:Z
    healthcheck:
      test: pg_isready --dbname='immich' --username='immich' || exit 1; Chksum="\$\$(psql --dbname='immich' --username='immich' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $\$Chksum"; [ "$\$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="\$\$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: on-failure
    networks:
      - immich

networks:
  immich:
    external: true