site:
  base_domain: ""
  timezone: ""
  homeassistant_zigbee_router_serial_id: ""
backup:
  s3_endpoint: ""
  s3_region: ""
  s3_bucket: ""
  s3_prefix: ""
  s3_access_key_id: ""
  s3_secret_access_key: ""
  repository_password: ""
caddy:
  cloudflare_api_token: ""
  bookmarks_password_hash: ""
forgejo:
  database_password: ""
homeassistant:
  mosquitto_password: ""
immich:
  database_password: ""
radicale:
  htpasswd_record: ""
searxng:
  secret_key: ""
supernote:
  database_root_password: ""
  database_user_password: ""
  valkey_password: ""
vaultwarden:
  admin_token_hash: ""
