backup:
  s3_access_key_id: ""
  s3_secret_access_key: ""
  repository_password: ""
caddy:
  cloudflare_api_token: ""
  bookmarks_password_hash: ""
docs_mcp:
  openai_api_key: ""
  posthog_api_key: ""
forgejo:
  database_password: ""
homeassistant:
  mosquitto_password: ""
immich:
  database_password: ""
radicale:
  htpasswd_record: ""
searxng:
  secret_key: ""
supernote:
  database_root_password: ""
  database_user_password: ""
  redis_password: ""
vaultwarden:
  admin_token_hash: ""
